### ISSUE TITLE
Look of tables cannot be changed in a dashboard

### ISSUE THREAD

**Issue by PaulPoulain** [biblibre/urungi#115]
In dashboard building, the font size of table is 30px by default. That's large. If you change for something smaller (like 14px), it works. But save the dashboard, exit, re-open => back to 30px
Steps to reproduce :
- create a dashboard
- create a table report
- add a 2 rows layout
- add the report in a dashboard area
- the table is very large. Click the report > Text style > change 30px to 14px, the color to red and alignment to right > Save
- exit dashboard > re-edit
- back to 30px, black, left align

**Comment by clrh** [comment]
Probably the same problem:
* Add a filter to a report, display it in dashboard
* Style it 
* Save
* Come back, the filter is not styled anymore

**Comment by jajm** [comment]
> Probably the same problem:
>   [...]

Not exactly the same, I created a new issue for that : #120
