### ISSUE TITLE
Displaying reports in dashboards is broken

### ISSUE THREAD

**Issue by clrh** [biblibre/urungi#118]
**Describe the bug**
A dashboard can't display reports.

**To Reproduce**
* Create a report
* Include it in dashboard
* Save and display it

**Expected behavior**
See the reports in a dashboards...

**Screenshots**
![Sélection_126](https://user-images.githubusercontent.com/471280/63514308-9d2dec00-c4e8-11e9-8aab-9d0a4a821ddd.png)

** Version
* Master at this moment

**Comment by PaulPoulain** [comment]
Maybe I have the same problem : https://suivi-urungi.biblibre.com/#/dashboards/view/5d53c1bc0b45895434a3f4eb => the last (bottom right) report has been added recently, and never appear.

**Comment by clrh** [comment]
"It works now for me"

I just upgraded:
```
$ git show-branch master origin/master
* [master] Update CHANGELOG.md
 ! [origin/master] Add missing 'type' property in mongoose schema for reports
--
 + [origin/master] Add missing 'type' property in mongoose schema for reports
 + [origin/master^] Fix a bug preventing to change the sort direction in report editor
 + [origin/master~2] 1.2.0
 + [origin/master~3] Update CHANGELOG
 + [origin/master~4^2] Fix some graphical issues with grid and vGrid in dashboards
 + [origin/master~5^2] Fix icon for date fields in report editor
 + [origin/master~6^2] Fix isUsable check in report editor
 + [origin/master~7^2] Do not send data to /api/reports/get-data
 + [origin/master~7^2^] Fix queries with multiple filters
*+ [master] Update CHANGELOG.md

$  git rebase origin/master

$  NODE_ENV=production npx migrate-mongo status
```

@PaulPoulain maybe it is good for you too ?

**Comment by PaulPoulain** [comment]
good for me too, closing
