### ISSUE TITLE
"repainting report" appearing, should not

### ISSUE THREAD

**Issue by PaulPoulain** [biblibre/urungi#125]
**Describe the bug**
When you start a graph (pie for example), if you change the type of graph, a "repainting report" appears even if you don't have other parameters
**To Reproduce**
- Start a report, type donut
- Drop a metric
- Select 'count' for this metric (optional)
- Select 'pie' instead of donut
=> a Repainting report appear, with a turning wheel. Let you think that Urungi is doing something, but in fact it's doing nothing (except throwing an error "query is undefined" n the console logs)

**Expected behavior**
repaint the report only when the user clic on 'redraw', that appear when all parameters are set.

**Comment by jajm** [comment]
@PaulPoulain I think it was fixed by #130. Can you confirm ?
