### ISSUE TITLE
 The title of the report is not saved

### ISSUE THREAD

**Issue by fcatrice** [biblibre/urungi#141]
**Describe the bug**

When editing a report and changing only the title, the "Save" button does not work.

**Comment by PaulPoulain** [comment]
I suspect that you missed the way it work:
 * update the title
 * <enter>
 * save
I agree it's boring, and I've been crazy 1000x times about this stupid behavior.

If I'm right, edit the title of this report "title not saved unless you <enter>". It's so annoying that it should be fixed ! (but it's minor, easy to workaround)
