### ISSUE TITLE
background-color of a report, white in edit while transparent in run

### ISSUE THREAD

**Issue by PaulPoulain** [biblibre/urungi#148]
Create a dashboard, add a 2 reports layout, add a report on each
The background color seems to be white :
![image](https://user-images.githubusercontent.com/4696271/66318084-f5933e80-e91a-11e9-8318-82e7fb5cc6de.png)

But when you run the report, the background is transparent:
![image](https://user-images.githubusercontent.com/4696271/66318055-e90ee600-e91a-11e9-8776-50841acac8f0.png)

If you manually force background to white, it's saved and appears white as expected. IE: the default is 'no background' but in editor, a white background is used.
PS: not sure there's a way to remove a background color once you're selected one

**Comment by jajm** [comment]
Fixed by 90c4ae6500a6d573cb7315646b150fbd0b6bdec8
