### ISSUE TITLE
Make it possible to enable HTTPS

### ISSUE THREAD

**Issue by alexkhudyshkin** [biblibre/urungi#196]
It would be great if we can run Urungi over https://.
This guide may be useful: https://www.sitepoint.com/how-to-use-ssltls-with-node-js/

**Comment by jajm** [comment]
It's already possible using a reverse proxy like Nginx. What would be the benefits of implementing it at the nodejs level ?

**Comment by alexkhudyshkin** [comment]
Not sure, didn't think about nginx, sorry for the stupid question!
