### ISSUE TITLE
User control issues

### ISSUE THREAD

**Issue by alexkhudyshkin** [biblibre/urungi#198]
**Is your feature request related to a problem? Please describe.**
There are several issues related to user control. Currently you cannot stop a user from using Urungi after he logged in.

**Describe the solution you'd like**

### 1. Making user 'not active' in the User list should make his session break immediately. 
_Currently 'not active' just makes it so you cannot login anymore - but you can never log out so basically it does not stop user from using Urungi._

**Steps to reproduce**:
1. Create a user
2. Log in with this user in another browser session
3. Go back to administrator session and make this user 'not active'
4. Refresh the page in user's session - you can still use Urungi
**Expected behavior:** user is redirected to the login page

### 2. 'Shared space permission' in Roles does not really provide you Execution rights.
_They just give you the rights to see the link to a report. Once you have a link, you don't need this rights to execute the report._

**Steps to reproduce:**
1. Create a report
2. Create a shared space
3. Put the report into a shared space
4. Create a role
5. Give this role 'Execute reports' rights in 'shared space permission' tab on the shared space you created in step 2.
6. Create a user
7. Assign the role you created in step 4 to the user
8. Log in with this user in another browser session
9. Execute the report from the shared space that you see
10. Go back to administrator session and remove the role from the user.
11. Refresh the report page in the user's session - you can still use it.
**Expected behavior:** user gets 404 'Not Found' error

### 3. Make it possible to delete a user

Currently you can only make it inactive.

**Comment by jajm** [comment]
@alexkhudyshkin thanks for reporting these problems.

As they are different from each other, I will open a new issue for each and close this one.
