### ISSUE TITLE
Dashboard creation, no 'limit' when putting a report on the dashboard

### ISSUE THREAD

**Issue by PaulPoulain** [biblibre/urungi#20]
When you add a report on a dashboard, a preview is made. There's no 'limit' used when building the preview. On large dataset, you have to wait a long time before seing the result. Automatically limit the sample to X first results (configurable)

- draw only when clicking new 'Redraw' button
- rename  'Refresh' (-> Redraw) button in report edition

**Comment by golbian** [comment]
branch : control-run
