### ISSUE TITLE
error 502 on a long query

### ISSUE THREAD

**Issue by PaulPoulain** [biblibre/urungi#216]
A dashboard running a long query never give any result (turning wheel turning forever)
Browser logs show a 502 error.
I've attached a dashboard failing on the Loire Forez database, that is quite large (5M lines in statistics table)
The dashboard is here : https://pro.calf.prod.biblibre.com/urungi/dashboards/view/5df1fa549ef5612943b114cf

**Comment by PaulPoulain** [comment]
[DLL-E2-error502.zip](https://github.com/biblibre/urungi/files/3955383/DLL-E2-error502.zip)

**Comment by jajm** [comment]
Fixed by 414bd5826323308625b20208aa0b3b7bbc51de64
