### ISSUE TITLE
can't get collection when connecting to oracledb

### ISSUE THREAD

**Issue by helxsz** [biblibre/urungi#220]
i am using tableplus to connect the oracle database, it is working well.
but when I am using urungi to connect to this database and retrieve all the collection of the database.

the code for this is 

```
        query = (knex) =>
            knex.select({
                table_schema: knex.raw('user'),
                name: 'TABLE_NAME'
            }).from('USER_TABLES').unionAll(function () {
                this.select({
                    table_schema: knex.raw('user'),
                    name: 'VIEW_NAME'
                }).from('USER_VIEWS');
            }).orderBy('name');
```

the server returns a error 

> { Error: ORA-00936: missing expression }

what problem it could be ?

**Comment by jajm** [comment]
@helxsz Which version of Oracle Database are you using ?
