### ISSUE TITLE
urungi dont print all dashboards for user with role "voir"

### ISSUE THREAD

**Issue by ldsbiblibre** [biblibre/urungi#222]
**Describe the bug**
urungi dont pring all dashboards for user with role "voir"

**To Reproduce**
1. Go to https://pro-devurungi-koha.support.biblibre.eu/urungi/
2. Click on login with administrator/O77ugdTC5Y
3. Show the home page, you see  Shared Area(DLL,Tableaux,Transition bibliographique)
4. Delog
5. Click on login with bibliotheque/090llksdrN
6. Show the home page, you see  Shared Area(DLL)

**Expected behavior**
The user "bibliotheque" have role->voir with execute dashboard and execute reports on Tableaux,Transition bibliographique like DLL in share space permission. he must be able to see them

**Comment by jajm** [comment]
Fixed by 1f89a36c849145fa539bc50e18526975871fc88b
