### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by cfuhr** [biblibre/urungi#239]
**Spanish translation**

Hello, my name is Claudio and I want to thank you for your work and I would like to make a contribution to Urungi since the application is only in English and French is that I made the translation into Spanish.
I am from Argentina and together with other people we are trying to get the university libraries that use Koha to know Urungi to make their statistics.
Attached file es.po and screenshot.
Best regards.

--
Claudio M. Fuhr

[es.zip](https://github.com/biblibre/urungi/files/4498348/es.zip)
![Urungi_Spanish_translate](https://user-images.githubusercontent.com/14838455/79679623-bd2fbf80-81dd-11ea-915c-cda2f6ee48d7.png)

**Comment by jajm** [comment]
Thanks! Your contribution is very much appreciated.
I pushed the translation in master (74bb0bfa659835b0391f08ce33f3203433375325), so it will be available in the next release.

**Comment by cfuhr** [comment]
Hi Julian, I send the file es.po again because I corrected a couple of errors.
Sorry and thanks for adding my contribution.

Claudio

[es.zip](https://github.com/biblibre/urungi/files/4533155/es.zip)

**Comment by jajm** [comment]
It's pushed, thanks ;)
