### ISSUE TITLE
Order keys do not work unless they are also selected in the result

### ISSUE THREAD

**Issue by claudietregouet** [biblibre/urungi#249]
Description : 
Using the "Only show the first XX elements" filters does not work in a report with an order key.

To Reproduce
- create a report
- choose the columns' display
- drop several fields in the columns. One of them should be a count. (for example, fieldA, fieldB, count(fieldC).
- Drop field C in the order key 
- Put "5" in the "Quick display with" field
- Click on "filter" > "Only show the first 5 elements" should appears in the filters
- Click on "draw" / "redraw"

=> "Fetching data" is displayed without results
![urungi filter](https://user-images.githubusercontent.com/67108465/85028277-264e9780-b17b-11ea-8184-0f32aa1b363a.png)

**Comment by PaulPoulain** [comment]
I just tested, and I don't think it's the "only show the first XX element" that is the culprit.
The same report without the filter does not work.
So I think it's the count(X) as field and X as sort who is buggy.

Fix 1 => if you sort on a field that is in the field list, automatically apply the grouping condition if there is one
OR
Fix 2 => be able to drag & drop a field from the field list into the sort area (which result in a "copy" not a "move")
OR
Fix 3 => have a wheel in the sort field where you can chose the grouping (usually the same as in the field list, but there can be some uncommon case where they're different)

**Comment by ThibaudGLT** [comment]
fix merged
