### ISSUE TITLE
Tables don't appear in "source" of layers

### ISSUE THREAD

**Issue by jcastillee** [biblibre/urungi#250]
**Describe the bug**
Hello, i have connected urungi with my databse with success (MySql) and i would like to create layers. When i go to "layers/sources" i find the name of my database but when i click on it, nothing happens (tables don't appear).. 
Pls someone got an idea ? 

**Screenshots**
![image](https://user-images.githubusercontent.com/68337590/87555522-db5e6c00-c6b5-11ea-8198-c28b0f64c801.png)

**Server (please complete the following information):**
 - OS: Ubuntu 20.04
 - Datasource(s): MySql

**Comment by jajm** [comment]
Ah, a problem with the `only_full_group_by` SQL mode...

It might take a while before I have a chance to look at it. As a workaround, you can disable this mode in MySQL configuration (https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html)

**Comment by jcastillee** [comment]
Thanks for the fast answer, but it still doesn't work. 
I changed the sqlmode as you indicated  by doing : 

mysql > SET sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));
then my variable changed in : STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION

I restart urungi and the bug persists, i'm not able to see my tables in the database.

**Comment by jajm** [comment]
Do you have a new error message in logs ?

**Comment by jcastillee** [comment]
Hi, 
no error message at all, 
everything seems to be ok...

**Comment by jajm** [comment]
Can you look at your web browser console ? There might be useful messages here.

**Comment by jcastillee** [comment]
Yes effectively, when i click on the name of my database, there is the last error message  : 

Error: [ngRepeat:dupes] http://errors.angularjs.org/1.7.9/ngRepeat/dupes?p0=collectionName%20in%20item.entities&p1=object%3Anull&p2=null
    at bundle.min.js:15
    at bundle.min.js:337
    at bundle.min.js:158
    at m.$digest (bundle.min.js:159)
    at m.$apply (bundle.min.js:163)
    at k (bundle.min.js:114)
    at v (bundle.min.js:119)
    at XMLHttpRequest.y.onload (bundle.min.js:120)

![image](https://user-images.githubusercontent.com/68337590/87641259-2032e300-c748-11ea-84f4-d0f1b3cb00de.png)

**Comment by jcastillee** [comment]
I searched some solutions to errors but nothing came out from internet. Pls help ? I really don't know how to proceed...

**Comment by jajm** [comment]
Can you share a small dump of your database, so I can try to reproduce ?
Which version of MySQL are you using ?

**Comment by jcastillee** [comment]
[dump.pdf](https://github.com/biblibre/urungi/files/4936874/dump.pdf)
my version of MySql is 8.0.20,

**Comment by jcastillee** [comment]
[MySQL dump 10.docx](https://github.com/biblibre/urungi/files/4936942/MySQL.dump.10.docx)
sorry there was a pb with the previous file

**Comment by jajm** [comment]
Can you upload a plain SQL file ? Or even better a gzipped version of that plain SQL file ?

**Comment by jcastillee** [comment]
[dump.zip](https://github.com/biblibre/urungi/files/4937425/dump.zip)
is that ok ?

**Comment by jajm** [comment]
> [dump.zip](https://github.com/biblibre/urungi/files/4937425/dump.zip)
> is that ok ?

Yes, thanks

**Comment by jcastillee** [comment]
Hi, after several attempts i decide to dl Urungi with Docker Compose on my VM, and the bug disappears. 
Just in case of someone meet the same issue...
Thanks !
