### ISSUE TITLE
Report filters don't apply to xlsx exports

### ISSUE THREAD

**Issue by Quitra01** [biblibre/urungi#252]
**Describe the bug**
When a filter is applied to a report, the changes can be seen on the report screen but when exporting to xlsx, the filters don't apply.

**To Reproduce**
1. Open a report that will produce 0 results with default filters
2. Apply filters that will produce results
3. Export xlsx
4. See that the file is empty

**Expected behavior**
The export should happen with current files

**Server (please complete the following information):**
 - OS: Docker Compose on Ubuntu 18.04
 - MongoDB: 4.2.6
 - Datasource(s): MySQL

**Client (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome  85.0.4183.102
**Additional context**
I've tried various filters, it does not seem to depend on the filter used. I think this will really get in the way of people using urungi.

**Comment by PaulPoulain** [comment]
Thanks for the report @Quitra01 . Do you plan to provide a fix ? Welcome on board though, I hope you'll enjoy urungi !

**Comment by Quitra01** [comment]
Thank you for the welcome, I had time to check it out today and made a fix with https://github.com/biblibre/urungi/pull/253. I made it check the current filters before getting the data. I'll probably write some tests for it when I have the time this weekend.
