### ISSUE TITLE
Currency format symbol doesn't appear

### ISSUE THREAD

**Issue by Marie74300** [biblibre/urungi#255]
**Describe the bug**
When you change the format for a currency with the symbol of this one, the symbol doesn't appear

**To Reproduce**
1. Go to a report with a price
2. Click on the field of price 
3. Change his format for '0,0[.]00 $' and save
4. Refresh the report, see error the $ does'nt appear

**Expected behavior**
After change format field the symbol need to appear in your data
**Screenshots**
![image](https://user-images.githubusercontent.com/45934574/120325565-11b1d3
![image](https://user-images.githubusercontent.com/45934574/120325620-21311c80-c2e8-11eb-90c4-435538c1f229.png)
80-c2e8-11eb-93a5-63f4274c1e7d.png)

**Server (please complete the following information):**
 - OS: [e.g. Debian 10]
 - NodeJS: [e.g. 10.17.0]
 - MongoDB: [e.g. 3.6.15]
 - Datasource(s): [e.g. MariaDB 10.1]

**Client (please complete the following information):**
 - OS: [e.g. Debian 10]
 - Browser [e.g. Firefox 60 ESR]

**Additional context**

**Comment by ThibaudGLT** [comment]
I try to reproduce the behavior but all working fine for me, did you pull the latest stable version ? 
![price_issue_urungi](https://user-images.githubusercontent.com/64733561/129158670-a69e18e5-24a5-4e5f-ab47-19ab9f5a65cd.gif)
