### ISSUE TITLE
Replace Noty

### ISSUE THREAD

**Issue by jajm** [biblibre/urungi#264]
[Noty](https://github.com/needim/noty) is no longer supported.

We should replace it by something else.

**Comment by ThibaudGLT** [comment]
### Replacement choices
To replace _Noty_, we've seen plenty of alternatives and here are the reasons we didn't choose them:
- [_angular-toastr_](https://github.com/Foxandxss/angular-toastr) : doesn't be maitain anymore
- [_toastr_](https://github.com/CodeSeven/toastr) : doesn't be maintain anymore
-  [_izitoast_](https://github.com/marcelodolza/iziToast) : doesn't support bootstrap4 natively
- [_notifyJS_](https://github.com/jpillora/notifyjs) : old repo activity

_PNotify_ actually choose offer many options of style, behavior and displaying this is why we chose it.
