### ISSUE TITLE
Entering a date

### ISSUE THREAD

**Issue by PaulPoulain** [biblibre/urungi#28]
When you put a filter on a date, you get a date selector, but it's impossible to enter manually a date. finding an old date is highly time consuming, we need to be able to enter the date.
    there is a graphic glitch (see screenshot)

![image](https://user-images.githubusercontent.com/4696271/55730808-51871400-5a19-11e9-843d-5816ce409b7f.png)

**Comment by golbian** [comment]
branch : input-date on biblibre.
