### ISSUE TITLE
export to PDF error with pikitia

### ISSUE THREAD

**Issue by oliviercrouzet** [biblibre/urungi#325]
Hello
I can't get the pdf export to work with Pikitia.
I have created, as indicated a client_id and a client_secret in mongodb.
The pdf export with pikitia systematically produces the following error message
0|urungi   | FetchError: invalid json response body at https://[kohahost]:8080/pikitia/oauth/token reason: Unexpected token < in JSON at position 0
0|urungi   |     at /home/koha/urungi/node_modules/node-fetch/lib/index.js:273:32
0|urungi   |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|urungi   |     at async render (/home/koha/urungi/server/helpers/pikitia.js:56:19)
0|urungi   |     at async /home/koha/urungi/server/custom/reports/routes.js:70:28

I suppose it's more a configuration problem (my notions about node.js are rather short...).
Urungi works correctly. Urungi and pikitia are installed in a web sub-folder of a Koha test instance with a redirection in nginx this way :
location /urungi/ {
    proxy_pass       http://localhost:8083/;
}

location /pikitia {
   proxy_pass       http://localhost:3000;
}

pikitia parameters in config/default.js (https://[kohahost]:8080 = url of our koha staff instance):
    pikitia: {
        url: 'https://[kohahost]:8080/pikitia',
        client_id: OUR_CLIENT_ID,
        client_secret: OUR_CLIENT_SECRET,
    }

urungi config  in config/development.js :
module.exports = {
    url: 'http://localhost',
    ip: '0.0.0.0',
    port: 8083,
    db: 'mongodb://localhost:27017/urungi_development',
};

Does anyone have any idea how to solve the problem ?

Olivier

**Comment by jajm** [comment]
Do you have any error message on the Pikitia side ?

**Comment by oliviercrouzet** [comment]
I have some warnings when I launch pikitia :
```
Listening on port: 3000
(node:29303) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:29303) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
(node:29303) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
(node:29303) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
Connected to mongodb://localhost/pikitia_development
```
and when I try to export to pdf, only this line that mentions the POST request :

**Comment by jajm** [comment]
> and when I try to export to pdf, only this line that mentions the POST request :
> `::ffff:127.0.0.1 bacrungi POST /pikitia/oauth/token HTTP/1.0 404 159 - 3.125 ms`

That's the problem, pikitia itself should only see a request to `/oauth/token` not `/pikitia/oauth/token`
Try adding a trailing slash in your nginx configuration, like this: `location /pikitia/ {`

**Comment by oliviercrouzet** [comment]
I already tried to add slash but that makes no difference. same errors urungi side and same pikitia site :
::ffff:127.0.0.1 bacrungi POST /pikitia/oauth/token HTTP/1.0 404 159 - 3.125 ms.

**Comment by jajm** [comment]
Have you tried to add a trailing slash to the proxy_pass argument too ? I don't remember exactly how, but nginx behaviour differs when you add these slashes

**Comment by oliviercrouzet** [comment]
Yes I did this too and had no success. The path displayed in first line seems to match the expected path (/oauth/token)  you told me  about but the following lines speak now about invalid client ?!! :
```
::ffff:127.0.0.1 bacrungi POST /oauth/token HTTP/1.0 401 1402 - 84.820 ms

invalid_client: Invalid client: client is invalid
    at new InvalidClientError (/home/koha/pikitia/node_modules/oauth2-server/lib/errors/invalid-client-error.js:26:14)
    at /home/koha/pikitia/node_modules/oauth2-server/lib/handlers/token-handler.js:159:15
    at tryCatcher (/home/koha/pikitia/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/koha/pikitia/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/koha/pikitia/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/koha/pikitia/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/koha/pikitia/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/home/koha/pikitia/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/koha/pikitia/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/koha/pikitia/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (node:internal/timers:466:21)
```
As I had an underscore in my client_secret, I suspected a problem of forbidden character and replace it by a letter but uselessly.
Is there any constraint about client_secret format ?
I add I have inserted the client_id-client_secret pair in mongo prompt as explained in the API section of Pikitia Readme.

**Comment by jajm** [comment]
Please verify that you followed all instructions at https://github.com/biblibre/pikitia#installation and https://github.com/biblibre/pikitia#chromium-headless-shell-dependencies to install the headless browser needed to take screenshots

**Comment by oliviercrouzet** [comment]
the OS is Debian stretch

**Comment by jajm** [comment]
Now that you added the missing dependencies, does it work ?

**Comment by oliviercrouzet** [comment]
No, I had already added the needed dependancies (according to the pikitia instructions) before getting  the last error lines i mentionned

**Comment by jajm** [comment]
Ok, so maybe you need to update your kernel, as advised by this message:

> No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.

On my dev machine Pikitia runs well on Debian buster with Linux 5.10

**Comment by oliviercrouzet** [comment]
I followed below instructions and that's ok for the sandbox problem now.
https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#alternative-setup-setuid-sandbox

Unfortunately, if  the pdf is produced now, it 's empty (with a "404 Not Found" title). Suppose the path of source is not correct (cause of redirection ?)

**Comment by oliviercrouzet** [comment]
Ok I got it. The url in my config/development.js was not correct :
module.exports = {
    url: 'http://localhost',
    ip: '0.0.0.0',
    port: 8083,
    db: 'mongodb://localhost:27017/urungi_development',
};
I put instead the url of the koha instance :
module.exports = {
    url: 'https://[kohahost]:8080
    ip: '0.0.0.0',
    port: 8083,
    db: 'mongodb://localhost:27017/urungi_development',
};

Many thanks for your patient help.
