### ISSUE TITLE
Fix issues reported by LGTM

### ISSUE THREAD

**Issue by stweil** [biblibre/urungi#51]
LGTM reports several issues with the latest Urungi code:
https://lgtm.com/projects/g/biblibre/urungi/alerts/?mode=list.

**Comment by jajm** [comment]
Most issues are fixed now.

There is still the 'Missing CSRF middleware' error that requires a bit more thought

**Comment by jajm** [comment]
> There is still the 'Missing CSRF middleware' error that requires a bit more thought

New issue created for this specific problem #60
