### ISSUE TITLE
Show totals in tables (grid, vgrid, cross tables)

### ISSUE THREAD

**Issue by jajm** [biblibre/urungi#74]
In cross tables, display totals of all columns and rows
In grids and vgrids, add ability to define a list of columns where the total should be calculated

**Comment by PaulPoulain** [comment]
display total of column / rows mus be a parameter: sometimes it's needed, sometimes not.
So it should be something like:
- columns 'show total' / 'no total'
- lines 'show total' / 'no total'
If both are shown a grand total is displayed as well.
