### ISSUE TITLE
Useless scroll bars (H and V) in dashboard

### ISSUE THREAD

**Issue by PaulPoulain** [biblibre/urungi#83]
Edit DLL - D1 - Imprimés et D2 ...
The crossed reports are small, but they have scrollbars, horizontal and vertical, that are useless.
I tried to update the size of the graph, the container, could make them disappear, until I redraw the result.
![image](https://user-images.githubusercontent.com/4696271/59526953-8791ba00-8eda-11e9-9fc2-7e7d54f336fd.png)

**Comment by PaulPoulain** [comment]
maybe fixed by #136 ?

**Comment by jajm** [comment]
@PaulPoulain is this issue still valid ? I cannot reproduce the problem.
