### ISSUE TITLE
ODBC | JDBC driver

### ISSUE THREAD

**Issue by ComputingFroggy** [biblibre/urungi#88]
It would be nice to increase the number of RDBMs to connect to.
May be, a "simple" way would be to implement an ODBC or JDBC driver that can already connect to multiple RDBMs.

carry on the good work

**Comment by jajm** [comment]
Hi @ComputingFroggy 

Support for Oracle JDBC driver was just removed from master (see https://github.com/biblibre/urungi/blob/master/CHANGELOG.md#111---2019-07-12)

I don't think we will introduce new connectors anytime soon, especially if it requires a JDK and a C/C++ compiler toolchain

But I think it would be great to be able to add new connectors through some kind of plugins system, without having to touch the core.
